// ─────────────────────────────────────────────────────────────────────────────
// AuditSnapshotsPage.jsx — audit evidence snapshots (/reports/snapshots).
//
// Generate panel (admin/manager only — mirrors the server's requireManager
// gate on POST /api/compliance/snapshots): pick a standard scope (all, or one
// code from GET /api/compliance/summary) and a site scope (all, or one from
// GET /api/sites), then POST {standardCode?, siteId?}. The response carries
// the snapshot's SHA-256, which the server anchors in the tamper-evident
// audit log at generation time — the toast surfaces the hash prefix.
//
// History: GET /api/compliance/snapshots → data.snapshots (+ pagination).
// Each row: date, kind badge (standard scope vs EMP document), scope,
// generated by, size, sha256 (copy-to-clipboard), and an authed PDF download
// via GET /api/compliance/snapshots/:id/download. Kind filter chips narrow
// the history (server-side via ?kind=, with a defensive client-side filter).
//
// EMP panel: NFPA 70B:2023 §4.2 requires a written Electrical Maintenance
// Program document. POST /api/compliance/emp-document renders it from live
// system data, anchors its hash in the audit log (kind 'emp'), and the page
// auto-downloads the PDF.
// ─────────────────────────────────────────────────────────────────────────────

import { useCallback, useEffect, useState } from 'react';
import { BookOpenCheck, Copy, Download, FileCheck2, ShieldCheck } from 'lucide-react';
import api from '../api/client';
import { useAuth } from '../context/AuthContext';
import { useDocumentTitle } from '../hooks/useDocumentTitle';
import BackLink from '../components/BackLink';
import { downloadAuthedFile } from '../api/download';
import Toast from '../components/Toast';
import EmptyState from '../components/EmptyState';

function fmtBytes(n) {
  if (n == null || Number.isNaN(Number(n))) return '—';
  const num = Number(n);
  if (num < 1024) return `${num} B`;
  if (num < 1024 * 1024) return `${(num / 1024).toFixed(1)} KB`;
  return `${(num / (1024 * 1024)).toFixed(1)} MB`;
}

// Date + time — snapshots can be generated multiple times a day, so the
// date-only house fmtDate() isn't enough here.
function fmtDateTime(d) {
  if (!d) return '—';
  const dt = new Date(d);
  if (Number.isNaN(dt.getTime())) return '—';
  return dt.toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' });
}

export default function AuditSnapshotsPage() {
  useDocumentTitle('Audit snapshots');
  const { user } = useAuth();
  // requireManager-equivalent gate for snapshot generation.
  const canGenerate = ['admin', 'manager'].includes(user?.role);

  const [standards, setStandards] = useState([]); // codes from /api/compliance/summary
  const [sites, setSites]         = useState([]);
  const [stdCode, setStdCode]     = useState(''); // '' = all standards
  const [siteId, setSiteId]       = useState(''); // '' = all sites
  const [generating, setGenerating] = useState(false);
  const [generatingEmp, setGeneratingEmp] = useState(false);
  const [kindFilter, setKindFilter] = useState(''); // '' | 'standard' | 'emp'

  const [snapshots, setSnapshots] = useState([]);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState('');
  const [toast, setToast]         = useState(null);

  useEffect(() => {
    api.get('/api/compliance/summary')
      .then(r => {
        const codes = (r.data?.data?.summary || [])
          .map(row => row.standard?.code)
          .filter(Boolean);
        setStandards([...new Set(codes)]);
      })
      .catch(() => { /* picker just offers "All standards" */ });
    api.get('/api/sites')
      .then(r => setSites(r.data?.data?.sites || []))
      .catch(() => { /* picker just offers "All sites" */ });
  }, []);

  const fetchSnapshots = useCallback(() => {
    // Server-side kind filter where supported; the render path also filters
    // client-side so an older server that ignores ?kind= still behaves.
    const params = kindFilter ? { kind: kindFilter } : {};
    return api.get('/api/compliance/snapshots', { params })
      .then(r => setSnapshots(r.data?.data?.snapshots || []))
      .catch(err => setError(err.response?.data?.error || 'Failed to load snapshot history.'));
  }, [kindFilter]);

  useEffect(() => {
    setLoading(true);
    fetchSnapshots().finally(() => setLoading(false));
  }, [fetchSnapshots]);

  async function handleGenerate() {
    if (generating || !canGenerate) return;
    setGenerating(true);
    setToast({ message: 'Generating snapshot — rendering the PDF and anchoring its hash…', variant: 'info', duration: 8000 });
    try {
      const body = {};
      if (stdCode) body.standardCode = stdCode;
      if (siteId) body.siteId = siteId;
      const res = await api.post('/api/compliance/snapshots', body);
      const snap = res.data?.data?.snapshot || {};
      const shaPrefix = (snap.sha256 || '').slice(0, 12);
      setToast({
        message: shaPrefix
          ? `Snapshot generated. Integrity hash recorded in audit log: ${shaPrefix}…`
          : 'Snapshot generated.',
        variant: 'success',
        duration: 10000,
      });
      fetchSnapshots();
    } catch (err) {
      setToast({ message: err.response?.data?.error || 'Failed to generate snapshot.', variant: 'error' });
    } finally {
      setGenerating(false);
    }
  }

  async function handleGenerateEmp() {
    if (generatingEmp || !canGenerate) return;
    setGeneratingEmp(true);
    setToast({ message: 'Generating EMP document — rendering from live system data and anchoring its hash…', variant: 'info', duration: 8000 });
    try {
      const res = await api.post('/api/compliance/emp-document');
      const snap = res.data?.data?.snapshot || {};
      const shaPrefix = (snap.sha256 || '').slice(0, 12);
      setToast({
        message: shaPrefix
          ? `EMP document generated. Integrity hash recorded in audit log: ${shaPrefix}… Your download is starting.`
          : 'EMP document generated. Your download is starting.',
        variant: 'success',
        duration: 10000,
      });
      fetchSnapshots();
      // Auto-download the freshly generated document.
      if (snap.id) {
        const base = import.meta.env.VITE_API_URL ?? '';
        downloadAuthedFile(
          `${base}/api/compliance/snapshots/${snap.id}/download`,
          snap.filename || 'emp-document.pdf',
        ).catch(err => setToast({ message: err.message || 'EMP document generated, but the download failed — use the History table below.', variant: 'warn' }));
      }
    } catch (err) {
      setToast({ message: err.response?.data?.error || 'Failed to generate the EMP document.', variant: 'error' });
    } finally {
      setGeneratingEmp(false);
    }
  }

  async function handleCopySha(sha) {
    try {
      await navigator.clipboard.writeText(sha);
      setToast({ message: 'SHA-256 hash copied to clipboard.', variant: 'success', duration: 4000 });
    } catch {
      setToast({ message: 'Could not access the clipboard.', variant: 'error' });
    }
  }

  async function handleDownload(snap) {
    try {
      const base = import.meta.env.VITE_API_URL ?? '';
      await downloadAuthedFile(
        `${base}/api/compliance/snapshots/${snap.id}/download`,
        snap.filename || 'compliance-snapshot.pdf',
      );
    } catch (err) {
      setToast({ message: err.message || 'Download failed.', variant: 'error' });
    }
  }

  const scopeLabel = (snap) => {
    if (isEmp(snap)) return 'Written maintenance program';
    const std = snap.standardCode || 'All standards';
    const site = snap.site?.name || (snap.siteId ? 'One site' : 'All sites');
    return `${std} · ${site}`;
  };

  // Defensive: older server payloads may omit `kind` — anything without
  // kind 'emp' is treated as a standard-scope compliance snapshot.
  const isEmp = (snap) => snap?.kind === 'emp';

  const visibleSnapshots = kindFilter
    ? snapshots.filter(s => (kindFilter === 'emp' ? isEmp(s) : !isEmp(s)))
    : snapshots;

  const KIND_FILTERS = [
    { key: '',         label: 'All kinds' },
    { key: 'standard', label: 'Compliance snapshots' },
    { key: 'emp',      label: 'EMP documents' },
  ];

  return (
    <>
      <div className="page-header">
        <div>
          <BackLink fallback="/reports" fallbackLabel="Reports" />
          <h1 className="page-title">Audit Evidence Snapshots</h1>
          <div className="page-subtitle">
            Point-in-time PDF compliance reports with cryptographic integrity hashes — evidence for an AHJ, insurer, or auditor.
          </div>
        </div>
      </div>

      <div className="page-body">
        {error && <div role="alert" className="alert alert-error mb-16">{error}</div>}

        {/* Integrity model note */}
        <div
          className="card"
          style={{
            padding: '12px 16px', marginBottom: 16,
            fontSize: 'var(--font-size-ui)', color: 'var(--color-text-secondary)',
            lineHeight: 1.55, borderLeft: '3px solid var(--color-primary)',
            display: 'flex', gap: 10, alignItems: 'flex-start',
          }}
        >
          <ShieldCheck size={18} color="var(--color-primary)" strokeWidth={1.75} style={{ flexShrink: 0, marginTop: 1 }} />
          <div>
            <strong style={{ color: 'var(--color-text)' }}>How integrity works.</strong>{' '}
            Each snapshot is stored immutably — it is never regenerated or edited after creation. Its SHA-256
            hash is anchored in the tamper-evident audit log at generation time, so an auditor can re-hash the
            downloaded PDF and verify it matches the hash recorded when the snapshot was made.
          </div>
        </div>

        {/* ── Generate panel ─────────────────────────────────────────────── */}
        <div className="card mb-16">
          <div className="card-header"><div className="card-title">Generate snapshot</div></div>
          <div className="card-body">
            <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'flex-end' }}>
              <div className="form-group" style={{ margin: 0, minWidth: 220 }}>
                <label htmlFor="snapshot-standard-scope" className="form-label">Standard scope</label>
                <select
                  id="snapshot-standard-scope"
                  className="form-control"
                  value={stdCode}
                  onChange={e => setStdCode(e.target.value)}
                  disabled={!canGenerate || generating}
                >
                  <option value="">All standards</option>
                  {standards.map(code => <option key={code} value={code}>{code}</option>)}
                </select>
              </div>
              <div className="form-group" style={{ margin: 0, minWidth: 220 }}>
                <label htmlFor="snapshot-site-scope" className="form-label">Site scope</label>
                <select
                  id="snapshot-site-scope"
                  className="form-control"
                  value={siteId}
                  onChange={e => setSiteId(e.target.value)}
                  disabled={!canGenerate || generating}
                >
                  <option value="">All sites</option>
                  {sites.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
                </select>
              </div>
              {canGenerate ? (
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={handleGenerate}
                  disabled={generating}
                >
                  {generating ? 'Generating…' : 'Generate snapshot'}
                </button>
              ) : (
                <div style={{ fontSize: 'var(--font-size-ui)', color: 'var(--color-text-secondary)', paddingBottom: 8 }}>
                  Only admins and managers can generate snapshots.
                </div>
              )}
            </div>
          </div>
        </div>

        {/* ── Generate EMP document panel ───────────────────────────────── */}
        <div className="card mb-16">
          <div className="card-header"><div className="card-title">Generate EMP document</div></div>
          <div className="card-body">
            <div
              style={{
                display: 'flex', gap: 10, alignItems: 'flex-start',
                fontSize: 'var(--font-size-ui)', color: 'var(--color-text-secondary)',
                lineHeight: 1.55, marginBottom: 12,
              }}
            >
              <BookOpenCheck size={18} color="var(--color-primary)" strokeWidth={1.75} style={{ flexShrink: 0, marginTop: 1 }} />
              <div>
                <strong style={{ color: 'var(--color-text)' }}>NFPA 70B:2023 §4.2 requires a written electrical maintenance program (EMP).</strong>{' '}
                This renders your EMP document from live system data — sites, equipment inventory, maintenance
                schedules, and program settings — and anchors its SHA-256 hash in the tamper-evident audit log,
                so the document you hand an auditor is provably the one generated here.
              </div>
            </div>
            {canGenerate ? (
              <button
                type="button"
                className="btn btn-primary"
                onClick={handleGenerateEmp}
                disabled={generatingEmp}
              >
                {generatingEmp ? 'Generating…' : 'Generate EMP document'}
              </button>
            ) : (
              <div style={{ fontSize: 'var(--font-size-ui)', color: 'var(--color-text-secondary)' }}>
                Only admins and managers can generate the EMP document.
              </div>
            )}
          </div>
        </div>

        {/* ── History ────────────────────────────────────────────────────── */}
        <div className="card mb-16">
          <div className="card-header" style={{ display: 'flex', alignItems: 'center', gap: 12, flexWrap: 'wrap' }}>
            <div className="card-title">History {visibleSnapshots.length > 0 && `(${visibleSnapshots.length})`}</div>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginLeft: 'auto' }} role="group" aria-label="Filter snapshots by kind">
              {KIND_FILTERS.map(f => {
                const active = kindFilter === f.key;
                return (
                  <button
                    key={f.key || 'all'}
                    type="button"
                    aria-pressed={active}
                    onClick={() => setKindFilter(f.key)}
                    style={{
                      padding: '3px 10px', borderRadius: 999, cursor: 'pointer',
                      fontSize: 'var(--font-size-xs)', fontWeight: 600,
                      background: active ? 'var(--color-primary-light, #eff6ff)' : 'var(--color-surface)',
                      color: active ? 'var(--color-primary)' : 'var(--color-text-secondary)',
                      border: `1px solid ${active ? 'var(--color-primary)' : 'var(--color-border)'}`,
                    }}
                  >
                    {f.label}
                  </button>
                );
              })}
            </div>
          </div>
          {loading ? (
            <div className="card-body"><div className="loading">Loading snapshot history…</div></div>
          ) : visibleSnapshots.length === 0 ? (
            <EmptyState
              icon={FileCheck2}
              title={kindFilter ? 'Nothing matches this filter' : 'No snapshots yet'}
              sub={kindFilter
                ? (kindFilter === 'emp'
                  ? 'No EMP documents generated yet — use the panel above.'
                  : 'No standard-scope compliance snapshots yet — use the Generate snapshot panel above.')
                : canGenerate
                  ? 'Generate your first audit evidence snapshot above — it lands here with its integrity hash.'
                  : 'Snapshots generated by admins and managers will appear here.'}
            />
          ) : (
            <div className="table-wrap">
              <table>
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Kind</th>
                    <th>Scope</th>
                    <th>Generated By</th>
                    <th style={{ textAlign: 'right' }}>Size</th>
                    <th>SHA-256</th>
                    <th style={{ textAlign: 'right' }}></th>
                  </tr>
                </thead>
                <tbody>
                  {visibleSnapshots.map(snap => (
                    <tr key={snap.id}>
                      <td style={{ whiteSpace: 'nowrap' }}>{fmtDateTime(snap.createdAt)}</td>
                      <td>
                        <span style={{
                          display: 'inline-block', padding: '2px 8px', borderRadius: 999,
                          fontSize: 'var(--font-size-xs)', fontWeight: 600, whiteSpace: 'nowrap',
                          background: isEmp(snap) ? '#eff6ff' : 'var(--color-surface)',
                          color: isEmp(snap) ? '#2563eb' : 'var(--color-text-secondary)',
                          border: `1px solid ${isEmp(snap) ? '#2563eb' : 'var(--color-border)'}`,
                        }}>
                          {isEmp(snap) ? 'EMP document' : 'Standard scope'}
                        </span>
                      </td>
                      <td>{scopeLabel(snap)}</td>
                      <td className="td-muted">{snap.generatedBy?.name || '—'}</td>
                      <td style={{ textAlign: 'right', whiteSpace: 'nowrap' }}>{fmtBytes(snap.sizeBytes)}</td>
                      <td>
                        {snap.sha256 ? (
                          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                            <code
                              title={snap.sha256}
                              style={{ fontSize: 'var(--font-size-xs)', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace' }}
                            >
                              {snap.sha256.slice(0, 12)}…
                            </code>
                            <button
                              type="button"
                              className="btn btn-secondary btn-sm"
                              onClick={() => handleCopySha(snap.sha256)}
                              title="Copy the full SHA-256 hash"
                              aria-label="Copy SHA-256 hash"
                              style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px' }}
                            >
                              <Copy size={12} />
                            </button>
                          </span>
                        ) : (
                          <span className="text-muted">—</span>
                        )}
                      </td>
                      <td style={{ textAlign: 'right' }}>
                        <button
                          type="button"
                          className="btn btn-secondary btn-sm"
                          onClick={() => handleDownload(snap)}
                          title={snap.filename ? `Download ${snap.filename}` : 'Download PDF'}
                          style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}
                        >
                          <Download size={13} />
                          Download
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
      <Toast toast={toast} onClose={() => setToast(null)} />
    </>
  );
}
