/**
 * QuoteRequests.jsx — Manager inbox for service quote requests.
 *
 * Shows all quote requests for the account with status tabs.
 * TELEMETRY_CRIT auto-generated requests display an "Auto-generated" badge
 * so reps understand these came from the condition-monitoring system.
 *
 * Manager+ only (role-gated in App.jsx via RequireRole).
 */
import { useEffect, useState, useCallback } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/client';

// ── Label helpers ────────────────────────────────────────────────────────────

const DRIVER_LABELS = {
  down_now:            { label: 'Down now',          color: '#dc2626' },
  suspected_failing:   { label: 'Suspected failing', color: '#d97706' },
  failed_inspection:   { label: 'Failed inspection', color: '#d97706' },
  planned_replacement: { label: 'Planned replacement', color: '#0ea5e9' },
  budgetary:           { label: 'Budgetary estimate', color: '#64748b' },
};

const TIMELINE_LABELS = {
  immediately:        'Immediately',
  within_1_week:      'Within 1 week',
  within_30_days:     'Within 30 days',
  next_budget_cycle:  'Next budget cycle',
};

const STATUS_COLORS = {
  draft:     { bg: 'var(--chip-slate-bg, #f1f5f9)', fg: 'var(--chip-slate-fg, #475569)' },
  requested: { bg: 'var(--chip-amber-bg, #fef3c7)', fg: 'var(--chip-amber-fg, #d97706)' },
  quoted:    { bg: 'var(--chip-blue-bg, #dbeafe)',  fg: 'var(--chip-blue-fg, #1d4ed8)' },
  accepted:  { bg: 'var(--chip-green-bg, #dcfce7)', fg: 'var(--chip-green-fg, #16a34a)' },
  declined:  { bg: 'var(--chip-red-bg, #fee2e2)',   fg: 'var(--chip-red-fg, #dc2626)' },
};

const TABS = [
  { key: '', label: 'All' },
  { key: 'requested', label: 'Requested' },
  { key: 'quoted',    label: 'Quoted' },
  { key: 'accepted',  label: 'Accepted' },
  { key: 'declined',  label: 'Declined' },
];

function fmtDate(iso) {
  if (!iso) return '—';
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function assetLabel(asset) {
  if (!asset) return '—';
  const base = [asset.manufacturer, asset.model].filter(Boolean).join(' ');
  const serial = asset.serialNumber ? ` #${asset.serialNumber}` : '';
  return base ? base + serial : (asset.equipmentType ?? 'Asset');
}

function StatusChip({ status }) {
  const c = STATUS_COLORS[status] ?? STATUS_COLORS.requested;
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '2px 8px', borderRadius: 999,
      background: c.bg, color: c.fg, fontSize: '0.72rem', fontWeight: 700, whiteSpace: 'nowrap' }}>
      {status.charAt(0).toUpperCase() + status.slice(1)}
    </span>
  );
}

function AutoBadge() {
  return (
    <span title="Auto-generated by condition-monitoring CRIT alert (NFPA 70B:2023)"
      style={{ display: 'inline-flex', alignItems: 'center', gap: 3, padding: '2px 7px', borderRadius: 999,
        background: 'var(--chip-blue-bg, #dbeafe)', color: 'var(--chip-blue-fg, #1d4ed8)',
        fontSize: '0.68rem', fontWeight: 700, marginLeft: 6, whiteSpace: 'nowrap' }}>
      ⚡ Auto
    </span>
  );
}

function EmergencyBadge() {
  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', padding: '2px 7px', borderRadius: 999,
      background: 'var(--chip-red-bg, #fee2e2)', color: 'var(--chip-red-fg, #dc2626)',
      fontSize: '0.68rem', fontWeight: 700, marginLeft: 6 }}>
      EMERGENCY
    </span>
  );
}

// ── Status update modal ──────────────────────────────────────────────────────

function StatusModal({ qr, onClose, onDone }) {
  const [status, setStatus] = useState(qr.status);
  const [note, setNote]   = useState(qr.quoteNotes || '');
  const [busy, setBusy]   = useState(false);
  const [err, setErr]     = useState('');

  const canNote = status === 'quoted';

  async function submit(e) {
    e.preventDefault(); setErr(''); setBusy(true);
    try {
      await api.patch(`/api/quote-requests/${qr.id}/status`, { status, quoteNotes: canNote ? note : undefined });
      onDone();
    } catch (ex) {
      setErr(ex?.response?.data?.error || 'Failed to update status.');
    } finally { setBusy(false); }
  }

  return (
    <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', zIndex: 1000,
      display: 'flex', alignItems: 'center', justifyContent: 'center' }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div style={{ background: 'var(--color-surface)', borderRadius: 10, padding: '24px 28px',
        width: '100%', maxWidth: 420, boxShadow: '0 8px 32px rgba(0,0,0,0.18)' }}>
        <h3 style={{ margin: '0 0 16px', fontSize: '1rem', fontWeight: 700 }}>Update quote status</h3>
        <form onSubmit={submit}>
          <div style={{ marginBottom: 14 }}>
            <label style={{ fontSize: '0.78rem', fontWeight: 600, display: 'block', marginBottom: 4 }}>Status</label>
            <select className="input" value={status} onChange={e => setStatus(e.target.value)} style={{ width: '100%' }}>
              {['requested','quoted','accepted','declined'].map(s => (
                <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
              ))}
            </select>
          </div>
          {canNote && (
            <div style={{ marginBottom: 14 }}>
              <label style={{ fontSize: '0.78rem', fontWeight: 600, display: 'block', marginBottom: 4 }}>Quote notes</label>
              <textarea className="input" value={note} onChange={e => setNote(e.target.value)} rows={3}
                placeholder="Add quote details, pricing, or next steps…" style={{ width: '100%', resize: 'vertical' }} />
            </div>
          )}
          {err && <div style={{ color: 'var(--chip-red-fg, #dc2626)', fontSize: '0.78rem', marginBottom: 10 }}>{err}</div>}
          <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
            <button type="button" className="btn btn-secondary btn-sm" onClick={onClose} disabled={busy}>Cancel</button>
            <button type="submit" className="btn btn-primary btn-sm" disabled={busy}>
              {busy ? 'Saving…' : 'Save'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// ── Main page ────────────────────────────────────────────────────────────────

export default function QuoteRequests() {
  const [activeTab, setActiveTab] = useState('');
  const [items, setItems]         = useState([]);
  const [total, setTotal]         = useState(0);
  const [loading, setLoading]     = useState(true);
  const [err, setErr]             = useState('');
  const [page, setPage]           = useState(1);
  const [editQR, setEditQR]       = useState(null); // open in modal

  const load = useCallback(async () => {
    setLoading(true); setErr('');
    try {
      const params = new URLSearchParams({ limit: '50', page: String(page) });
      if (activeTab) params.set('status', activeTab);
      const r = await api.get(`/api/quote-requests?${params}`);
      const d = r.data?.data ?? r.data;
      setItems(d.quoteRequests ?? []);
      setTotal(d.pagination?.total ?? 0);
    } catch (ex) {
      setErr(ex?.response?.data?.error || 'Failed to load quote requests.');
    } finally { setLoading(false); }
  }, [activeTab, page]);

  useEffect(() => { setPage(1); }, [activeTab]);
  useEffect(() => { load(); }, [load]);

  return (
    <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 0 40px' }}>
      {/* Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start',
        marginBottom: 20, flexWrap: 'wrap', gap: 8 }}>
        <div>
          <h1 style={{ margin: 0, fontSize: '1.35rem', fontWeight: 800 }}>Quote Requests</h1>
          <p style={{ margin: '4px 0 0', fontSize: '0.82rem', color: 'var(--color-text-secondary)' }}>
            Service quote requests from your facility — including auto-generated alerts from condition monitoring.
          </p>
        </div>
        <div style={{ fontSize: '0.78rem', color: 'var(--color-text-secondary)', paddingTop: 6 }}>
          {total > 0 && `${total} total`}
        </div>
      </div>

      {/* Status tabs */}
      <div style={{ display: 'flex', gap: 4, marginBottom: 20, flexWrap: 'wrap' }}>
        {TABS.map(t => (
          <button key={t.key} onClick={() => setActiveTab(t.key)}
            className={`btn btn-sm ${activeTab === t.key ? 'btn-primary' : 'btn-secondary'}`}
            style={{ fontWeight: activeTab === t.key ? 700 : 400 }}>
            {t.label}
          </button>
        ))}
      </div>

      {err && (
        <div className="card" style={{ padding: '12px 16px', color: 'var(--chip-red-fg, #dc2626)', marginBottom: 16, fontSize: '0.82rem' }}>
          {err}
        </div>
      )}

      {loading ? (
        <div style={{ color: 'var(--color-text-secondary)', fontSize: '0.85rem', padding: '24px 0' }}>Loading…</div>
      ) : items.length === 0 ? (
        <div className="card" style={{ padding: '32px 24px', textAlign: 'center' }}>
          <div style={{ fontSize: '0.95rem', fontWeight: 600, marginBottom: 6 }}>No quote requests{activeTab ? ` with status "${activeTab}"` : ''}</div>
          <div style={{ fontSize: '0.82rem', color: 'var(--color-text-secondary)' }}>
            Quote requests appear here when submitted from an asset detail page, or auto-generated when a telemetry CRIT alert fires.
          </div>
        </div>
      ) : (
        <div className="card" style={{ overflow: 'hidden', padding: 0 }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.83rem' }}>
            <thead>
              <tr style={{ background: 'var(--color-surface-2)' }}>
                {['Asset', 'Site', 'Driver', 'Timeline', 'Requested', 'Status', ''].map(h => (
                  <th key={h} style={{ textAlign: 'left', padding: '8px 12px', fontWeight: 700,
                    fontSize: '0.72rem', borderBottom: '1px solid var(--color-border)', whiteSpace: 'nowrap' }}>
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {items.map(qr => {
                const driverMeta = DRIVER_LABELS[qr.driver] ?? { label: qr.driver, color: '#64748b' };
                const isAuto = qr.triggerType === 'TELEMETRY_CRIT';
                const isEmergency = qr.emergencyMode || qr.driver === 'down_now';
                return (
                  <tr key={qr.id} style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <td style={{ padding: '10px 12px', maxWidth: 220 }}>
                      <div style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: 2 }}>
                        {qr.asset?.id ? (
                          <Link to={`/assets/${qr.asset.id}`} style={{ fontWeight: 600, color: 'var(--color-primary)' }}>
                            {assetLabel(qr.asset)}
                          </Link>
                        ) : (
                          <span style={{ fontWeight: 600 }}>Unknown asset</span>
                        )}
                        {isAuto && <AutoBadge />}
                        {isEmergency && <EmergencyBadge />}
                      </div>
                      {qr.requestedBy?.name && (
                        <div style={{ fontSize: '0.72rem', color: 'var(--color-text-secondary)', marginTop: 2 }}>
                          {isAuto ? 'System' : `by ${qr.requestedBy.name}`}
                        </div>
                      )}
                    </td>
                    <td style={{ padding: '10px 12px', color: 'var(--color-text-secondary)', whiteSpace: 'nowrap' }}>
                      {qr.asset?.site?.name ?? '—'}
                    </td>
                    <td style={{ padding: '10px 12px', whiteSpace: 'nowrap' }}>
                      <span style={{ color: driverMeta.color, fontWeight: 600, fontSize: '0.78rem' }}>
                        {driverMeta.label}
                      </span>
                    </td>
                    <td style={{ padding: '10px 12px', color: 'var(--color-text-secondary)', whiteSpace: 'nowrap' }}>
                      {TIMELINE_LABELS[qr.timeline] ?? qr.timeline ?? '—'}
                    </td>
                    <td style={{ padding: '10px 12px', color: 'var(--color-text-secondary)', whiteSpace: 'nowrap' }}>
                      {fmtDate(qr.createdAt)}
                    </td>
                    <td style={{ padding: '10px 12px', whiteSpace: 'nowrap' }}>
                      <StatusChip status={qr.status} />
                    </td>
                    <td style={{ padding: '10px 12px', whiteSpace: 'nowrap' }}>
                      <button className="btn btn-secondary btn-sm"
                        onClick={() => setEditQR(qr)}>
                        Update
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Pagination */}
      {total > 50 && (
        <div style={{ display: 'flex', gap: 8, justifyContent: 'center', marginTop: 16, alignItems: 'center' }}>
          <button className="btn btn-secondary btn-sm" disabled={page === 1} onClick={() => setPage(p => p - 1)}>← Prev</button>
          <span style={{ fontSize: '0.82rem', color: 'var(--color-text-secondary)' }}>Page {page}</span>
          <button className="btn btn-secondary btn-sm" disabled={items.length < 50} onClick={() => setPage(p => p + 1)}>Next →</button>
        </div>
      )}

      {/* Status update modal */}
      {editQR && (
        <StatusModal qr={editQR} onClose={() => setEditQR(null)} onDone={() => { setEditQR(null); load(); }} />
      )}
    </div>
  );
}
