#!/usr/bin/env node
'use strict';

/**
 * scripts/sbom-sync.js
 * --------------------
 * Copies the most recent SBOM (CycloneDX + SPDX) from
 * `docs/security/scans/<latest-date>/sbom-server.*` into `server/sbom/`
 * so the docker build context (which is `./server`) can include them.
 *
 * Run before `docker compose build` whenever a fresh SBOM has been
 * generated by syft. The Dockerfile copies `server/sbom/` into the
 * image at /app/sbom/.
 *
 * Why a script and not a symlink: Docker's COPY can't follow symlinks
 * out of the build context. Why not git submodules: same reason, plus
 * the SBOM is a derived artifact that we want versioned alongside the
 * code that produced it.
 *
 * Usage:
 *   npm run sbom:sync
 *   npm run sbom:sync -- --date 2026-05-03   # pin to a specific scan date
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCANS_DIR = path.join(REPO_ROOT, 'docs', 'security', 'scans');
const SERVER_SBOM_DIR = path.join(REPO_ROOT, 'server', 'sbom');

function pickDate(argv) {
  const idx = argv.indexOf('--date');
  if (idx >= 0 && argv[idx + 1]) return argv[idx + 1];
  // Pick the lexically-greatest YYYY-MM-DD directory under scans/ — works
  // because ISO dates sort chronologically.
  if (!fs.existsSync(SCANS_DIR)) {
    throw new Error(`scans dir missing: ${SCANS_DIR}`);
  }
  const dates = fs
    .readdirSync(SCANS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter((n) => /^\d{4}-\d{2}-\d{2}$/.test(n))
    .sort();
  if (dates.length === 0) {
    throw new Error(`no dated scan dirs under ${SCANS_DIR}`);
  }
  return dates[dates.length - 1];
}

function main() {
  const date = pickDate(process.argv);
  const src = path.join(SCANS_DIR, date);
  const cdx = path.join(src, 'sbom-server.cdx.json');
  const spdx = path.join(src, 'sbom-server.spdx.json');

  if (!fs.existsSync(cdx) || !fs.existsSync(spdx)) {
    throw new Error(
      `SBOM files missing for ${date}: expected sbom-server.cdx.json + sbom-server.spdx.json under ${src}`
    );
  }

  fs.mkdirSync(SERVER_SBOM_DIR, { recursive: true });
  fs.copyFileSync(cdx, path.join(SERVER_SBOM_DIR, 'cyclonedx.json'));
  fs.copyFileSync(spdx, path.join(SERVER_SBOM_DIR, 'spdx.json'));

  // Drop a tiny sidecar that tells operators which scan date is shipped.
  fs.writeFileSync(
    path.join(SERVER_SBOM_DIR, 'README.md'),
    [
      '# ServiceCycle Server SBOM',
      '',
      `Source: \`docs/security/scans/${date}/sbom-server.{cdx,spdx}.json\``,
      `Synced via \`npm run sbom:sync\` on ${new Date().toISOString()}.`,
      '',
      'CycloneDX (cyclonedx.json) is the primary format; SPDX (spdx.json)',
      "is provided for ecosystems that prefer it. Both list every direct +",
      'transitive Node dependency the runtime image carries.',
      '',
      'To regenerate, run `syft scan dir:server` from the repo root and',
      'check the new files into the next `docs/security/scans/<date>/`.',
      '',
    ].join('\n')
  );

  console.log(`[sbom:sync] copied SBOMs for ${date} -> server/sbom/`);
}

main();
