'use strict';

/**
 * proposalPdf.ts — renders a multi-year maintenance proposal (#5) to a PDF
 * Buffer. Mirrors lib/cfoReport pdfkit stream-hardening (error handler bound
 * before any write, footer recursion guard, settled flag) and co-brand support.
 *
 *   renderProposalPdf(data, meta) -> Promise<Buffer>
 */

const PDFDocument = require('pdfkit');

const COLORS = {
  bgDark: '#0a0d12', textOnDark: '#ffffff', textOnDarkMuted: '#9aa3b2',
  text: '#0a0d12', textMuted: '#5b6373', textSubtle: '#9aa3b2',
  border: '#dde2eb', accent: '#0d4f6e', cardBg: '#fafbfd',
  replace: '#b91c1c', repair: '#b45309', defer: '#5b6373',
};
const FONT_REG = 'Helvetica', FONT_BOLD = 'Helvetica-Bold', FONT_OBL = 'Helvetica-Oblique';
const PAGE = { margin: 54, width: 612, height: 792, contentW: 504 };
const BOTTOM = PAGE.height - PAGE.margin;

function fmtMoney(n: any) {
  if (n == null || !Number.isFinite(Number(n))) return '—';
  return '$' + Math.round(Number(n)).toLocaleString('en-US');
}
const range = (r: any) => `${fmtMoney(r.min)} – ${fmtMoney(r.max)}`;

function drawFooter(doc: any, meta: any, pageNum: number) {
  if (doc._renderingFooter) return;
  doc._renderingFooter = true;
  try {
    const y = doc.page.height - PAGE.margin + 10;
    doc.moveTo(PAGE.margin, y).lineTo(doc.page.width - PAGE.margin, y).strokeColor(COLORS.border).lineWidth(0.5).stroke();
    doc.fillColor(COLORS.textSubtle).font(FONT_REG).fontSize(8)
       .text(`${meta.brandName ? meta.brandName + ' · ' : ''}Generated by ServiceCycle — ${meta.generatedAtIso}`, PAGE.margin, y + 4, { align: 'left', lineBreak: false });
    doc.fillColor(COLORS.textSubtle).font(FONT_REG).fontSize(8)
       .text(`Page ${pageNum}`, PAGE.margin, y + 4, { align: 'right', lineBreak: false });
  } finally { doc._renderingFooter = false; }
}

function optionCard(doc: any, x: number, y: number, w: number, opt: any, highlight: boolean) {
  const h = 64;
  doc.rect(x, y, w, h).fill(highlight ? '#eef5f9' : COLORS.cardBg);
  doc.rect(x, y, w, h).strokeColor(highlight ? COLORS.accent : COLORS.border).lineWidth(highlight ? 1.25 : 0.75).stroke();
  doc.fillColor(COLORS.text).font(FONT_BOLD).fontSize(10).text(opt.label, x + 8, y + 8, { width: w - 16, lineBreak: false });
  doc.fillColor(COLORS.accent).font(FONT_BOLD).fontSize(13).text(range(opt.total), x + 8, y + 24, { width: w - 16, lineBreak: false });
  doc.fillColor(COLORS.textMuted).font(FONT_REG).fontSize(8).text(`${opt.count} line item${opt.count === 1 ? '' : 's'}`, x + 8, y + 44, { width: w - 16, lineBreak: false });
}

function renderProposalPdf(data: any, meta: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margins: { top: PAGE.margin, bottom: PAGE.margin, left: PAGE.margin, right: PAGE.margin },
      info: { Title: `Multi-Year Maintenance Proposal — ${data.accountName}`, Author: 'ServiceCycle', Creator: 'ServiceCycle proposal builder' },
    });

    const chunks: any[] = [];
    let settled = false;
    const fail = (err: any) => { if (settled) return; settled = true; try { doc.destroy(); } catch {} reject(err instanceof Error ? err : new Error(String(err))); };
    doc.on('error', fail);
    doc.on('data', (c: any) => chunks.push(c));
    doc.on('end', () => { if (settled) return; settled = true; resolve(Buffer.concat(chunks)); });

    let pageNum = 1;
    doc.on('pageAdded', () => { pageNum += 1; drawFooter(doc, meta, pageNum); });

    try {
      doc.rect(0, 0, doc.page.width, 96).fill(meta.brandColor || COLORS.bgDark);
      doc.fillColor(COLORS.textOnDark).font(FONT_BOLD).fontSize(22).text(meta.brandName || 'ServiceCycle', PAGE.margin, 26, { lineBreak: false });
      doc.fillColor(COLORS.textOnDarkMuted).font(FONT_REG).fontSize(12).text('Multi-Year Maintenance Proposal', PAGE.margin, 56, { lineBreak: false });

      let y = 120;
      doc.fillColor(COLORS.text).font(FONT_BOLD).fontSize(16).text(`Prepared for ${data.accountName}`, PAGE.margin, y, { width: PAGE.contentW });
      y = doc.y + 2;
      doc.fillColor(COLORS.textMuted).font(FONT_REG).fontSize(10).text(`${data.scope.siteName ? data.scope.siteName + ' · ' : ''}Generated ${meta.generatedAtIso}`, PAGE.margin, y, { width: PAGE.contentW });
      y = doc.y + 16;

      // Option cards.
      doc.fillColor(COLORS.text).font(FONT_BOLD).fontSize(13).text('Program options', PAGE.margin, y); y = doc.y + 8;
      const gw = (PAGE.contentW - 24) / 3;
      (data.options || []).slice(0, 3).forEach((opt: any, i: number) => {
        optionCard(doc, PAGE.margin + i * (gw + 12), y, gw, opt, opt.key === 'recommended');
      });
      y += 64 + 18;

      // Line item table.
      doc.fillColor(COLORS.text).font(FONT_BOLD).fontSize(13).text('Scope of work', PAGE.margin, y); y = doc.y + 8;
      const cols = [
        { k: 'asset', w: 210, label: 'Asset' },
        { k: 'rec', w: 70, label: 'Action' },
        { k: 'year', w: 50, label: 'Year' },
        { k: 'cost', w: 174, label: 'Est. cost' },
      ];
      const drawHeader = () => {
        doc.font(FONT_BOLD).fontSize(8).fillColor(COLORS.textMuted);
        let cx = PAGE.margin;
        for (const c of cols) { doc.text(c.label.toUpperCase(), cx, y, { width: c.w, lineBreak: false }); cx += c.w; }
        y = doc.y + 4;
        doc.moveTo(PAGE.margin, y).lineTo(PAGE.margin + PAGE.contentW, y).strokeColor(COLORS.border).lineWidth(0.5).stroke();
        y += 4;
      };
      drawHeader();
      for (const li of data.lineItems) {
        if (y > BOTTOM - 24) { doc.addPage(); y = PAGE.margin; drawHeader(); }
        const recColor = COLORS[li.recommendation as 'replace' | 'repair' | 'defer'] || COLORS.text;
        let cx = PAGE.margin;
        doc.font(FONT_REG).fontSize(9).fillColor(COLORS.text).text(li.assetLabel + (li.siteName ? ` (${li.siteName})` : ''), cx, y, { width: cols[0].w - 6 }); cx += cols[0].w;
        const rowTop = y;
        doc.font(FONT_BOLD).fontSize(9).fillColor(recColor).text(li.recommendation.toUpperCase(), cx, rowTop, { width: cols[1].w - 6, lineBreak: false }); cx += cols[1].w;
        doc.font(FONT_REG).fontSize(9).fillColor(COLORS.text).text(String(li.year), cx, rowTop, { width: cols[2].w - 6, lineBreak: false }); cx += cols[2].w;
        doc.font(FONT_REG).fontSize(9).fillColor(COLORS.text).text(`${fmtMoney(li.costMin)} – ${fmtMoney(li.costMax)}`, cx, rowTop, { width: cols[3].w, lineBreak: false });
        y = Math.max(doc.y, rowTop + 12) + 4;
      }
      y += 8;

      // Total.
      if (y > BOTTOM - 30) { doc.addPage(); y = PAGE.margin; }
      doc.font(FONT_BOLD).fontSize(11).fillColor(COLORS.text).text(`Total program (5-year): ${range(data.summary.total)}`, PAGE.margin, y, { width: PAGE.contentW });
      y = doc.y + 14;

      // Disclaimer.
      if (y > BOTTOM - 70) { doc.addPage(); y = PAGE.margin; }
      const disText = data.disclaimer;
      doc.font(FONT_REG).fontSize(9);
      const disH = doc.heightOfString(disText, { width: PAGE.contentW - 24, lineGap: 2 }) + 28;
      doc.rect(PAGE.margin, y, PAGE.contentW, disH).fill('#fffbeb');
      doc.rect(PAGE.margin, y, 3, disH).fill(COLORS.repair);
      doc.rect(PAGE.margin, y, PAGE.contentW, disH).strokeColor('#fde68a').lineWidth(0.75).stroke();
      doc.fillColor('#92400e').font(FONT_BOLD).fontSize(9).text('SCOPE & LIMITATIONS', PAGE.margin + 12, y + 8, { width: PAGE.contentW - 24, lineBreak: false });
      doc.fillColor(COLORS.text).font(FONT_REG).fontSize(9).text(disText, PAGE.margin + 12, y + 22, { width: PAGE.contentW - 24, lineGap: 2 });

      drawFooter(doc, meta, 1);
      doc.end();
    } catch (err) { fail(err); }
  });
}

module.exports = { renderProposalPdf };

export {};
